name: deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      url: ${{ steps.url.outputs.url}}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      - name: Upload to releases
        uses: softprops/action-gh-release@v1
        id: upload-releases
        with:
          tag_name: release
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/libs/lumivoid-servers.jar

      - name: Show download id
        id: url
        run: echo "url=${{ fromJSON(steps.upload-releases.outputs.assets)[0].browser_download_url }}" >> "$GITHUB_OUTPUT"

  deploy:
    name: deploy to server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Connect to server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: false
          script: |
            cd /home/${{ secrets.USERNAME }}/lumivoid-servers/ &&
            rm lumivoid-servers.jar &&
            wget ${{ needs.build.outputs.url }} &&
            reboot